name: Deploy to Render.com
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Set up Python
    uses: actions/setup-python@v3
    with:
      python-version: 3.x
  - name: Install Dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  - name: Deploy
    if: github.ref == 'refs/heads/main'
    run: |
      curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.RENDER_DEPLOYMENT_HOOK }}"
